### ISSUE TITLE
Continue button not working

### ISSUE THREAD

**Issue by ayaangrover** [Brushfire-257/Horizon-Driving#1]
In the v0.2 beta, after playing a game, none of the buttons click, you have to close and re-open the app.

**Comment by SharKingStudios** [comment]
Were the buttons misaligned or were you using a screen that is not 1920 x 1080?
There is a known scaling issue that will be fixed in the next release, it causes the buttons to not display in the correct spots for non 1920x1080 size screens. (If you click where the buttons are supposed to be it should still take the input)

**Comment by ayaangrover** [comment]
Oh, that must be it - I have 15 inch display, and the buttons seemed misaligned. When I hover where the buttons should be, this works. Thanks!

**Comment by SharKingStudios** [comment]
Ok perfect!
